# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-11-09 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_staff_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='email',
        ),
    ]
